spring.datasource.url=jdbc:postgresql://136.115.146.17:5432/ticketapp_db
spring.datasource.username=ticketapp_user
spring.datasource.password=BGUticketapp1!

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect