#spring.datasource.url=jdbc:postgresql://136.115.146.17:5432/ticketapp_db?connectTimeout=5

spring.datasource.username=ticketapp_user
spring.datasource.password=BGUticketapp1!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# HikariCP
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.keepalive-time=60000

# ??? ??? ????? ?????? ???? ???????
#spring.datasource.hikari.connection-timeout=10000

# ??? ??? ????? ?????? ?????
spring.datasource.hikari.validation-timeout=3000

# ??????? ?? ??????
spring.datasource.hikari.idle-timeout=600000

# ????? ???????
spring.datasource.hikari.max-lifetime=1800000

# ???? ??????
spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.maximum-pool-size=10

# Initial State
initial.state.file=initial-state.txt
initial.state.skipExisting=true
initial.state.reset=true
initial.state.enabled=true

# Repository
repository.type=DB

# Schedulers
spring.task.scheduling.enabled=false

#spring.datasource.hikari.maximum-pool-size=15
#spring.datasource.hikari.connection-timeout=15000
spring.datasource.hikari.leak-detection-threshold=30000
spring.datasource.url=jdbc:postgresql://136.115.146.17:5432/ticketapp_db?connectTimeout=5
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.connection-timeout=15000
external.system.url=https://damp-lynna-wsep-1984852e.koyeb.app/