/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim': '#101415',
        'on-primary-container': '#798098',
        'outline-variant': '#45464d',
        'secondary': '#e9c349',
        'secondary-container': '#af8d11',
        'inverse-on-surface': '#2d3133',
        'outline': '#909097',
        'surface-container-low': '#191c1e',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        'primary': '#bec6e0',
        'tertiary-container': '#390008',
        'tertiary': '#ffb3b3',
        'on-secondary': '#3c2f00',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'background': '#101415',
        'surface-container-highest': '#323537',
        'primary-container': '#0f172a',
        'surface': '#101415',
        'secondary-fixed': '#ffe088',
        'on-surface': '#e0e3e5',
        'error-container': '#93000a',
        'on-primary': '#283044',
        'secondary-fixed-dim': '#e9c349',
        'surface-container': '#1d2022',
        'on-background': '#e0e3e5',
        'surface-container-high': '#272a2c',
        'inverse-primary': '#565e74',
        'surface-container-lowest': '#0b0f10',
        'inverse-surface': '#e0e3e5',
        'surface-variant': '#323537',
        'on-tertiary-container': '#e24b58',
        'on-surface-variant': '#c6c6cd',
        'surface-bright': '#363a3b',
        'on-tertiary': '#680015',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max-width': '1280px',
        'margin-desktop': '64px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'unit': '4px',
      },
      maxWidth: {
        'container-max-width': '1280px',
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
